name: common-nodejs
on:
 workflow_call:
  inputs:
   project:
    required: true
    type: string
   component:
    required: true
    type: string
   app_type:
    required: true
    type: string
jobs:
 ci:
  runs-on: self-hosted
  steps:
    - name: checkout code
      uses: actions/checkout@v5
    - name: list files
      run: ls -l
    - name: print inputs
      run: echo "project is {{ inputs.project }}"

       