name: common-nodejs
on:
 workflow_call:
  inputs:
   project:
    required: true
    type: string
   component:
    required: true
    type: string
   app_type:
    required: true
    type: string
  secrets:
   AWS_ACCESS_KEY_ID:
    required: true
   AWS_SECRET_ACCESS_KEY:
    required: true
jobs:
 ci:
  runs-on: self-hosted
  steps:
    - name: checkout code
      uses: actions/checkout@v5
    - name: list files
      run: ls -l
    - name: print inputs
      run: echo "project is ${{ inputs.project }}"
    - name: read app version
      id: package-version
      run: echo "version=$(cat package.json | jq -r '.version')" >> $GITHUB_OUTPUT
    - name: print app version
      run: echo ${{ steps.package-version.outputs.version }}
    - name: install dependencies
      run: npm install
    - name: build docker image
      run: docker build -t 448049818055.dkr.ecr.us-east-1.amazonaws.com/${{ inputs.project }}/${{ inputs.component }}:${{ steps.package-version.outputs.version }} .
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Replace with your desired AWS region
    - name: push docker image
      run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 448049818055.dkr.ecr.us-east-1.amazonaws.com | docker push 448049818055.dkr.ecr.us-east-1.amazonaws.com/${{ inputs.project }}/${{ inputs.component }}:${{ steps.package-version.outputs.version }}
       