name: common-nodejs
on:
 workflow_call:
  inputs:
   project:
    required: true
    type: string
   component:
    required: true
    type: string
   app_type:
    required: true
    type: string
jobs:
 ci:
  runs-on: self-hosted
  steps:
    - name: checkout code
      uses: actions/checkout@v5
    - name: list files
      run: ls -l
    - name: print inputs
      run: echo "project is ${{ inputs.project }}"
    - name: read app version
      id: package-version
      run: echo "version=$(cat package.json | jq -r '.version')" >> $GITHUB_OUTPUT
    - name: print app version
      run: echo ${{ steps.package-version.outputs.version }}

       